# Add 'label1' to any changes within 'example' folder or any subfolders
area/docs:
  - docs/**/*
  - ./*.md

area/testing:
  - tests/**/*

area/setup:
  - setup.py
  - extra-requirements.txt
  - requirements.txt
  - MANIFEST.in
  - fastentrypoints.py

area/core:
  - jina/**/*

area/helper:
  - jina/*.py

area/entrypoint:
  - jina/__init__.py


area/network:
  - jina/peapods/**/*
  - jina/proto/**/*

area/housekeeping:
  - .github/**/*
  - ./.gitignore

area/cicd:
  - .github/workflows/**/*

area/docker:
  - Dockerfiles/**/*
  - ./.dockerignore

area/cli:
  - jina_cli/**/*

area/docarray:
  - docarray/**/*

area/script:
  - script/**/*

component/client:
  - jina/clients/**/*

component/driver:
  - jina/drivers/**/*

component/executor:
  - jina/executors/**/*

component/docker:
  - jina/docker/**/*

executor/meta:
  - jina/executors/*.py

executor/encoder:
  - jina/executors/encoders/**/*

executor/indexer:
  - jina/executors/indexers/**/*

executor/ranker:
  - jina/executors/rankers/**/*

executor/crafter:
  - jina/executors/crafters/**/*

component/flow:
  - jina/flow/**/*

component/logging:
  - jina/logging/**/*

component/entrypoint:
  - jina/main/**/*

component/peapod:
  - jina/peapods/**/*

component/proto:
  - jina/proto/**/*

component/type:
  - jina/types/**/*

component/math:
  - jina/math/**/*

component/resource:
  - jina/resources/**/*

component/hub:
  - jina/hub/**/*

component/jaml:
  - jina/jaml/**/*