jtype: Flow
with:
  port: 12344
executors:
  - uses: Translator
    timeout_ready: -1
    py_modules:
      - executor.py
  - uses: jinaai://alaeddineabdessalem/TextToImage
    timeout_ready: -1
    install_requirements: true
