jtype: Flow
executors:
  - uses: jinaai+docker://alaeddineabdessalem/Translator
    timeout_ready: 1000000
  - uses: jinaai+docker://alaeddineabdessalem/TextToImage
    timeout_ready: 1000000
    jcloud:
      resources:
        gpu: 1
        memory: 16G
