apiVersion: apps/v1
kind: Deployment
metadata:
  name: {name}
  namespace: {namespace}
spec:
  replicas: {replicas}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {name}
  template:
    metadata:
      labels:
        app: {name}
        ns: {namespace}
    spec:
      volumes:
        - name: shared
          emptyDir: {}
      initContainers:
      - name: {init-name}
        image: {init-image}
        imagePullPolicy: {pull_policy}
        command: {init-command}
        volumeMounts:
          - name: shared
            mountPath: {mount-path}
      containers:
      - name: executor
        image: {image}
        command: {command}
        args: {args}
        ports:
          - containerPort: {port_expose}
          - containerPort: {port_in}
          - containerPort: {port_out}
          - containerPort: {port_ctrl}
        envFrom:
          - configMapRef:
              name: {name}-configmap
        volumeMounts:
          - name: shared
            mountPath: {mount-path}
        readinessProbe:
          tcpSocket:
            port: {port_in}
          initialDelaySeconds: 5
          periodSeconds: 10
