apiVersion: apps/v1
kind: Deployment
metadata:
  name: {name}
  namespace: {namespace}
spec:
  replicas: {replicas}
  selector:
    matchLabels:
      app: {name}
  template:
    metadata:
      labels:
        app: {name}
        ns: {namespace}
    spec:
      containers:
      - name: executor
        image: {image}
        imagePullPolicy: {pull_policy}
        command: {command}
        args: {args}
        ports:
          - containerPort: {port_expose}
          - containerPort: {port_in}
          - containerPort: {port_out}
          - containerPort: {port_ctrl}
        readinessProbe:
          tcpSocket:
            port: {port_in}
          initialDelaySeconds: 5
          periodSeconds: 10

#        livenessProbe:
#          exec:
#            command:
#              - python
#              - -c
#              - 'import os; import sys; from jina.peapods.runtimes.grpc import GRPCDataRuntime; control_port = int(os.getenv("JINA_EXECUTOR_CONTROL_PORT")); is_ready = GRPCDataRuntime.is_ready(ctrl_address=f"0.0.0.0:{str(control_port)}"); sys.exit(0) if is_ready else sys.exit(1)'
#          initialDelaySeconds: 30
#          periodSeconds: 60
        env:
          - name: JINA_LOG_LEVEL
            value: DEBUG
          - name: PYTHONUNBUFFERED
            value: "1"
          - name: WORKER_CLASS
            value: "uvicorn.workers.UvicornH11Worker"

