apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {name}
  namespace: {namespace}
  labels:
    app: {target}
spec:
  endpoints:
    - port: monitoring
  namespaceSelector:
    matchNames:
    - {namespace}
  selector:
    matchLabels:
      app: {target}