apiVersion: v1
kind: Service
metadata:
  name: {name}
  namespace: {namespace}
  labels:
    app: {target}
spec:
  type: {type}
  ports:
    - port: {port}
      targetPort: {port}
      name: {port-name}
      protocol: TCP
  selector:
    app: {target}