name: Jina CD

on:
  push:
    branches:
      - master

jobs:
  update-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v2
        with:
          MAX_HEADER_LEVEL: 3
          FOLDING: false
          GITHUB_TOKEN: ${{ secrets.JINA_AI }}
          TOC_TITLE: ''
          TARGET_PATHS: '*.md'
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - run: |
          pip install .
          ./make-doc.sh commit "${{github.event_name}} ${{github.sha}}"
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.JINA_AI }}
          repository: jina-ai/jina-docs
          force: true
          directory: docs/_build/html

  update-docker:
    needs: update-doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Available platforms
        run: |
          echo ${{ steps.buildx.outputs.platforms }}
          echo ::set-env name=VCS_REF::$(git rev-parse --short HEAD)
          echo ::set-env name=BUILD_DATE::$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo ::set-env name=JINA_VERSION::"$(sed '3q;d' ./jina/__init__.py | cut -d \' -f2)"
      - name: Run Buildx and Upload to Docker Cloud
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7,linux/arm/v6 \
            --output "type=registry" \
            --build-arg VCS_REF --build-arg BUILD_DATE --build-arg JINA_VERSION \
            -t jinaai/jina:master-debian -t jinaai/jina:dev-debian \
            --file ./Dockerfiles/debianx.Dockerfile .
