name: Update hub

on:
  workflow_dispatch:

jobs:
  update-jina-hub:
    runs-on: ubuntu-latest
    timeout-minutes: 600
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.JINA_DEV_BOT }}
      - env:
          GITHUB_TOKEN: ${{ secrets.JINA_DEV_BOT }}
          TAG_IN_ISSUES: '@jina-ai/engineering'
          MODULES_REPO: 'jina-ai/jina-hub'
        run: |
          sudo apt-get update -y
          sudo apt-get install python3.7 git python3-distutils python3-pip python3-setuptools -y
          echo `which python3.7`
          echo `which pip3`
          python3.7 -m pip install wheel --user
          python3.7 -m pip install gitpython ruamel.yaml PyGithub semver --user
          git clone --depth=1 https://$GITHUB_TOKEN@github.com/$MODULES_REPO
          python3.7 scripts/jina-hub-update.py
